// ============================================================
// Daily lead report — PDF rendering.
//
// Companion to buildReportText (qualify.ts): same data, but a proper
// document the team can open, print, and forward. Generated by the
// lead-report cron, uploaded to the public `reports` bucket, and sent
// to the team as a WhatsApp document.
// ============================================================

import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from 'pdf-lib'
import type { ScoredLead, LeadGrade } from './qualify'

const PAGE = { width: 595.28, height: 841.89 } // A4 portrait
const MARGIN = 48
const BODY_SIZE = 10
const LINE = 14

const GRADE_META: Record<LeadGrade, { label: string; color: ReturnType<typeof rgb> }> = {
  hot: { label: 'HOT — follow up today', color: rgb(0.78, 0.15, 0.11) },
  warm: { label: 'WARM — nurture', color: rgb(0.85, 0.5, 0.05) },
  cold: { label: 'COLD — keep on list', color: rgb(0.45, 0.45, 0.45) },
}

/**
 * pdf-lib's standard fonts are WinAnsi-only — a Telugu name would
 * throw at draw time. Strip anything outside that range; a name that
 * vanishes entirely falls back to the phone number, which is always
 * printed anyway.
 */
function toWinAnsi(text: string): string {
  return text.replace(/[^\x20-\x7E\xA0-\xFF]/g, '').replace(/\s{2,}/g, ' ').trim()
}

function wrap(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const words = text.split(/\s+/)
  const lines: string[] = []
  let current = ''
  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word
    if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
      current = candidate
    } else {
      if (current) lines.push(current)
      current = word
    }
  }
  if (current) lines.push(current)
  return lines
}

/** Render the day's scored leads as a single PDF document. */
export async function buildLeadReportPdf(
  leads: ScoredLead[],
  windowLabel: string,
): Promise<Uint8Array> {
  const doc = await PDFDocument.create()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)
  const contentWidth = PAGE.width - MARGIN * 2

  let page: PDFPage = doc.addPage([PAGE.width, PAGE.height])
  let y = PAGE.height - MARGIN

  const ensureRoom = (needed: number) => {
    if (y - needed < MARGIN) {
      page = doc.addPage([PAGE.width, PAGE.height])
      y = PAGE.height - MARGIN
    }
  }
  const drawLine = (
    text: string,
    opts: { font?: PDFFont; size?: number; color?: ReturnType<typeof rgb>; indent?: number } = {},
  ) => {
    const size = opts.size ?? BODY_SIZE
    ensureRoom(size + 4)
    page.drawText(text, {
      x: MARGIN + (opts.indent ?? 0),
      y,
      size,
      font: opts.font ?? font,
      color: opts.color ?? rgb(0.1, 0.1, 0.1),
    })
    y -= size + 4
  }

  // Header
  drawLine('Sri Manikanta Swamy Agri Farm', { font: bold, size: 16 })
  drawLine(`Daily Lead Report — ${windowLabel}`, { size: 12, color: rgb(0.3, 0.3, 0.3) })
  y -= 6
  const counts = {
    hot: leads.filter((l) => l.grade === 'hot').length,
    warm: leads.filter((l) => l.grade === 'warm').length,
    cold: leads.filter((l) => l.grade === 'cold').length,
  }
  drawLine(
    `${leads.length} enquiries in the last 24 hours: ${counts.hot} hot, ${counts.warm} warm, ${counts.cold} cold.`,
    { size: 11 },
  )
  y -= LINE

  if (leads.length === 0) {
    drawLine('No customer enquiries in this window.', { size: 11 })
  }

  for (const grade of ['hot', 'warm', 'cold'] as LeadGrade[]) {
    const group = leads.filter((l) => l.grade === grade)
    if (group.length === 0) continue
    ensureRoom(40)
    y -= 8
    drawLine(`${GRADE_META[grade].label} (${group.length})`, {
      font: bold,
      size: 12,
      color: GRADE_META[grade].color,
    })
    y -= 2
    for (const lead of group) {
      const name = toWinAnsi(lead.name ?? '') || '(no name)'
      ensureRoom(LINE * 2)
      drawLine(`${name} — ${lead.phone} — score ${lead.score}`, { font: bold, indent: 8 })

      const detail = (label: string, value: string | null) => {
        const clean = toWinAnsi(value ?? '')
        if (!clean) return
        for (const line of wrap(`${label}: ${clean}`, font, 9, contentWidth - 16)) {
          drawLine(line, { size: 9, color: rgb(0.25, 0.25, 0.25), indent: 16 })
        }
      }
      detail('Interested in', lead.products.join(', ') || null)
      detail('Place', lead.place)
      detail('Prefers', lead.preferences.join(', ') || null)
      detail('Signals', lead.signals.join('; ') || null)
      // Telugu messages strip to nothing under WinAnsi — detail() skips them.
      detail('Last message', lead.lastMessage ? `"${lead.lastMessage.slice(0, 160)}"` : null)
      y -= 4
    }
  }

  y = Math.max(y, MARGIN)
  page.drawText(
    `Generated ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} IST`,
    { x: MARGIN, y: MARGIN - 24, size: 8, font, color: rgb(0.6, 0.6, 0.6) },
  )

  return doc.save()
}
