-- ============================================================
-- 046_part_orders
--
-- Spare-part orders placed by customers in the WhatsApp chat.
-- The AI agent inserts a row when a customer confirms an order
-- ([[ORDER:...]] directive); the spare-parts team accepts or
-- declines by replying "OK <order_no>" / "NO <order_no>" on
-- WhatsApp, which the webhook maps back to this row and relays
-- to the customer.
--
-- Owner-only RLS, matching `parts` (037) and `appointments`
-- (038): the service role does all runtime writes.
--
-- Idempotent. Safe to run multiple times.
-- ============================================================

CREATE TABLE IF NOT EXISTS part_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Short human-friendly number the team quotes in replies ("OK 12").
  order_no BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  contact_id UUID REFERENCES contacts(id) ON DELETE SET NULL,
  conversation_id UUID REFERENCES conversations(id) ON DELETE SET NULL,
  part_number TEXT NOT NULL,
  part_name TEXT,
  qty INTEGER NOT NULL DEFAULT 1 CHECK (qty > 0),
  customer_phone TEXT,
  customer_name TEXT,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'accepted', 'declined', 'cancelled')),
  team_notified_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_part_orders_user_id ON part_orders(user_id);
CREATE INDEX IF NOT EXISTS idx_part_orders_status ON part_orders(user_id, status);

ALTER TABLE part_orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage own part orders" ON part_orders;
CREATE POLICY "Users can manage own part orders" ON part_orders
  FOR ALL USING (auth.uid() = user_id);

DROP TRIGGER IF EXISTS set_updated_at ON part_orders;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON part_orders
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
